/**
 * public/qqq-holdings.json is generated by GitHub Actions.
 * Shape:
 * {
 *   "source": "schwab",
 *   "asOfClose": "01/02/2026",
 *   "fetchedAtUtc": "2026-01-03T02:10:00Z",
 *   "holdings": [{ "symbol": "NVDA", "name": "NVIDIA Corp", "weightPct": 9.01 }]
 * }
 */
export async function loadQqqHoldings() {
  const res = await fetch(`${import.meta.env.BASE_URL}qqq-holdings.json`, { cache: "no-store" });
  if (!res.ok) throw new Error("Failed to load holdings JSON");
  const data = await res.json();

  const holdings = Array.isArray(data.holdings) ? data.holdings : [];
  return {
    source: data.source || "unknown",
    asOfClose: data.asOfClose || "",
    fetchedAtUtc: data.fetchedAtUtc || "",
    holdings: holdings
      .map(h => ({
        symbol: String(h.symbol || "").toUpperCase().trim(),
        name: String(h.name || "").trim(),
        weightPct: Number(h.weightPct) || 0
      }))
      .filter(h => h.symbol && h.weightPct > 0)
  };
}

export function topN(holdings, n) {
  return [...holdings].sort((a, b) => b.weightPct - a.weightPct).slice(0, n);
}

export function sumWeightsPct(holdings) {
  return holdings.reduce((acc, h) => acc + (Number(h.weightPct) || 0), 0);
}
